### PR TITLE
fix(types): correct type definitions

### PR DESCRIPTION
**Pull request by samchungy**
Changes:

- Fix type definitions
- Bump up @aws-sdk/client-dynamodb dev dependency version due to type errors https://github.com/aws/aws-sdk-js-v3/issues/1919
- Enable libcheck

### CODE REVIEW

**Review by freshollie — APPROVED** [review]
Looks great! Will get this merged and published.

Btw, is there any reason you have `skipLibCheck` enabled in your app? I always don't find it useful, though I can understand the use when publishing libraries.

**Comment by samchungy** [comment]
I guess it's one of those things which is enabled by default and `skipLibCheck` is the thing that overrides it? My workplace's rule of thumb is to keep it enabled, unless you really really need to disable it. I guess it helps weed out potential issues in other dependencies?

**Comment by samchungy** [comment]
I appreciate this library though, I got recommended to use this by a colleague and smashed out some tests today, so thanks a bunch man 🎉

**Comment by freshollie** [comment]
> I guess it helps weed out potential issues in other dependencies?

Yeah, I just dunno if that's useful. Typescript still checks how you use the signatures with it disabled.

> I got recommended to use this by a colleague and smashed out some tests today, so thanks a bunch man 

No worries! Glad it's of use to people!

**Comment by freshollie** [comment]
Interesting. CI didn't run on these commits 🤔

**Pull request merged**
